import { NgModule } from '@angular/core';
import {
  MatAccordion, MatAutocompleteModule,
  MatBadgeModule,
  MatButtonModule, MatBottomSheetModule,
  MatCardModule, MatButtonToggleModule,
  MatCheckboxModule, MatChipsModule,
  MatCommonModule, MatDatepickerModule,
  MatDialogModule,
  MatDividerModule, MatExpansionModule,
  MatMenuModule,
  MatSidenavModule, MatStepperModule, MatLineModule,
  MatIconModule, MatRadioModule, MatInputModule,
  MatSelectModule, MatFormFieldModule, MatGridListModule, MatNativeDateModule, MatOptionModule, MatToolbarModule,
  MatProgressSpinnerModule, MatRippleModule, MatTableModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatBottomSheetModule,
    MatCardModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatCommonModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatMenuModule,
    MatSidenavModule,
    MatStepperModule,
    MatLineModule,
    MatIconModule,
    MatRadioModule,
    MatInputModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatNativeDateModule,
    MatOptionModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatTableModule
  ],
  exports: [
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatBottomSheetModule,
    MatCardModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatCommonModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatMenuModule,
    MatSidenavModule,
    MatStepperModule,
    MatLineModule,
    MatIconModule,
    MatRadioModule,
    MatInputModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatNativeDateModule,
    MatOptionModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatTableModule
  ]
})
export class MaterialModule { }
